# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
-   repo: local
    hooks:
    - id: isort
      additional_dependencies:
        - isort
      name: isort
      entry: isort
      language: python
      types: [ python ]
      args: [--settings-path=setup.cfg]
    - id: black
      additional_dependencies:
        - black
      name: black
      entry: black
      language: python
      types: [python]
      args: ["--skip-string-normalization"]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [ python ]
      additional_dependencies: [wemake-python-styleguide]
      args: [ --config=setup.cfg]
    - id: mypy
      additional_dependencies:
        - fastapi==0.111.0
        - pydantic==2.7.1
        - pydantic-settings==2.2.1
        - passlib==1.7.4
        - asyncpg==0.29.0
        - psycopg2-binary==2.9.9
        - databases==0.9.0
        - alembic==1.13.1
        - sqlalchemy-utils==0.41.2
        - cryptography==42.0.2
        - python-jose==3.3.0
        - pytz==2024.1
        - types-pytz
        - bcrypt==4.1.3
        - mypy==1.10.0
        - python-dateutil
      name: mypy
      entry: mypy
      language: python
      types: [python]
      args: [--config-file=setup.cfg]
