version: '3.7'

services:
  postgres_adv:
    image: 'postgres:16-alpine3.19'
    container_name: 'postgres_adv'
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data/
    ports:
      - '8778:5432'
  redis:
    image: redis:5
    container_name: 'redis'
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  database_data:
  redis_data:
